//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tBaseElement">
 *
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iec.ch/61850/2006/SCL}tHeader"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2006/SCL}Substation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2006/SCL}Communication" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2006/SCL}IED" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2006/SCL}DataTypeTemplates" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "substation",
    "communication",
    "ied",
    "dataTypeTemplates"
})
@XmlRootElement(name = "SCL")
public class SCL
    extends TBaseElement
{

    @XmlElement(name = "Header", required = true)
    protected THeader header;
    @XmlElement(name = "Substation")
    protected List<TSubstation> substation;
    @XmlElement(name = "Communication")
    protected TCommunication communication;
    @XmlElement(name = "IED")
    protected List<TIED> ied;
    @XmlElement(name = "DataTypeTemplates")
    protected TDataTypeTemplates dataTypeTemplates;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link THeader }
     *     
     */
    public THeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link THeader }
     *     
     */
    public void setHeader(THeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the substation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSubstation }
     * 
     * 
     */
    public List<TSubstation> getSubstation() {
        if (substation == null) {
            substation = new ArrayList<TSubstation>();
        }
        return this.substation;
    }

    /**
     * Gets the value of the communication property.
     * 
     * @return
     *     possible object is
     *     {@link TCommunication }
     *     
     */
    public TCommunication getCommunication() {
        return communication;
    }



    /**
     * Sets the value of the communication property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCommunication }
     *     
     */
    public void setCommunication(TCommunication value) {
        this.communication = value;
    }

    /**
     * Gets the value of the ied property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ied property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIED().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TIED }
     * 
     * 
     */
    public List<TIED> getIED() {
        if (ied == null) {
            ied = new ArrayList<TIED>();
        }
        return this.ied;
    }

    /**
     * Gets the value of the dataTypeTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link TDataTypeTemplates }
     *     
     */
    public TDataTypeTemplates getDataTypeTemplates() {
        return dataTypeTemplates;
    }

    /**
     * Sets the value of the dataTypeTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataTypeTemplates }
     *     
     */
    public void setDataTypeTemplates(TDataTypeTemplates value) {
        this.dataTypeTemplates = value;
    }

}
