//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tAbstractDataAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAbstractDataAttribute">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tUnNaming">
 *       &lt;sequence>
 *         &lt;element name="Val" type="{http://www.iec.ch/61850/2006/SCL}tVal" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.iec.ch/61850/2006/SCL}tAttributeNameEnum" />
 *       &lt;attribute name="sAddr" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="bType" use="required" type="{http://www.iec.ch/61850/2006/SCL}tBasicTypeEnum" />
 *       &lt;attribute name="valKind" type="{http://www.iec.ch/61850/2006/SCL}tValKindEnum" default="Set" />
 *       &lt;attribute name="type" type="{http://www.iec.ch/61850/2006/SCL}tAnyName" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAbstractDataAttribute", propOrder = {
    "val"
})
@XmlSeeAlso({
    TBDA.class,
    TDA.class
})
public abstract class TAbstractDataAttribute
    extends TUnNaming
{

    @XmlElement(name = "Val")
    protected List<TVal> val;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "sAddr")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String sAddr;
    @XmlAttribute(name = "bType", required = true)
    protected String bType;
    @XmlAttribute(name = "valKind")
    protected TValKindEnum valKind;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "count")
    @XmlSchemaType(name = "unsignedInt")
    protected Long count;

    /**
     * Gets the value of the val property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the val property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TVal }
     * 
     * 
     */
    public List<TVal> getVal() {
        if (val == null) {
            val = new ArrayList<TVal>();
        }
        return this.val;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAddr() {
        return sAddr;
    }

    /**
     * Sets the value of the sAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAddr(String value) {
        this.sAddr = value;
    }

    /**
     * Gets the value of the bType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBType() {
        return bType;
    }

    /**
     * Sets the value of the bType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBType(String value) {
        this.bType = value;
    }

    /**
     * Gets the value of the valKind property.
     * 
     * @return
     *     possible object is
     *     {@link TValKindEnum }
     *     
     */
    public TValKindEnum getValKind() {
        if (valKind == null) {
            return TValKindEnum.SET;
        } else {
            return valKind;
        }
    }

    /**
     * Sets the value of the valKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link TValKindEnum }
     *     
     */
    public void setValKind(TValKindEnum value) {
        this.valKind = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getCount() {
        if (count == null) {
            return  0L;
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCount(Long value) {
        this.count = value;
    }

}
