//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAuthenticationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tAuthenticationEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="password"/>
 *     &lt;enumeration value="week"/>
 *     &lt;enumeration value="strong"/>
 *     &lt;enumeration value="certificate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tAuthenticationEnum")
@XmlEnum
public enum TAuthenticationEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("password")
    PASSWORD("password"),
    @XmlEnumValue("week")
    WEEK("week"),
    @XmlEnumValue("strong")
    STRONG("strong"),
    @XmlEnumValue("certificate")
    CERTIFICATE("certificate");
    private final String value;

    TAuthenticationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TAuthenticationEnum fromValue(String v) {
        for (TAuthenticationEnum c: TAuthenticationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
