//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tClientServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tClientServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="goose" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="gsse" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="bufReport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="unbufReport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="readLog" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tClientServices")
public class TClientServices {

    @XmlAttribute(name = "goose")
    protected Boolean goose;
    @XmlAttribute(name = "gsse")
    protected Boolean gsse;
    @XmlAttribute(name = "bufReport")
    protected Boolean bufReport;
    @XmlAttribute(name = "unbufReport")
    protected Boolean unbufReport;
    @XmlAttribute(name = "readLog")
    protected Boolean readLog;

    /**
     * Gets the value of the goose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoose() {
        if (goose == null) {
            return false;
        } else {
            return goose;
        }
    }

    /**
     * Sets the value of the goose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoose(Boolean value) {
        this.goose = value;
    }

    /**
     * Gets the value of the gsse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGsse() {
        if (gsse == null) {
            return false;
        } else {
            return gsse;
        }
    }

    /**
     * Sets the value of the gsse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGsse(Boolean value) {
        this.gsse = value;
    }

    /**
     * Gets the value of the bufReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBufReport() {
        if (bufReport == null) {
            return false;
        } else {
            return bufReport;
        }
    }

    /**
     * Sets the value of the bufReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBufReport(Boolean value) {
        this.bufReport = value;
    }

    /**
     * Gets the value of the unbufReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUnbufReport() {
        if (unbufReport == null) {
            return false;
        } else {
            return unbufReport;
        }
    }

    /**
     * Sets the value of the unbufReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnbufReport(Boolean value) {
        this.unbufReport = value;
    }

    /**
     * Gets the value of the readLog property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReadLog() {
        if (readLog == null) {
            return false;
        } else {
            return readLog;
        }
    }

    /**
     * Sets the value of the readLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadLog(Boolean value) {
        this.readLog = value;
    }

}
