//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tControlWithTriggerOpt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tControlWithTriggerOpt">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tControl">
 *       &lt;sequence>
 *         &lt;element name="TrgOps" type="{http://www.iec.ch/61850/2006/SCL}tTrgOps" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="intgPd" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tControlWithTriggerOpt", propOrder = {
    "trgOps"
})
@XmlSeeAlso({
    TReportControl.class,
    TLogControl.class
})
public abstract class TControlWithTriggerOpt
    extends TControl
{

    @XmlElement(name = "TrgOps")
    protected TTrgOps trgOps;
    @XmlAttribute(name = "intgPd")
    @XmlSchemaType(name = "unsignedInt")
    protected Long intgPd;

    /**
     * Gets the value of the trgOps property.
     * 
     * @return
     *     possible object is
     *     {@link TTrgOps }
     *     
     */
    public TTrgOps getTrgOps() {
        return trgOps;
    }

    /**
     * Sets the value of the trgOps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrgOps }
     *     
     */
    public void setTrgOps(TTrgOps value) {
        this.trgOps = value;
    }

    /**
     * Gets the value of the intgPd property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getIntgPd() {
        if (intgPd == null) {
            return  0L;
        } else {
            return intgPd;
        }
    }

    /**
     * Sets the value of the intgPd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIntgPd(Long value) {
        this.intgPd = value;
    }

}
