//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDomainLNGroupCEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDomainLNGroupCEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;pattern value="C[A-Z]*"/>
 *     &lt;enumeration value="CILO"/>
 *     &lt;enumeration value="CSWI"/>
 *     &lt;enumeration value="CALH"/>
 *     &lt;enumeration value="CCGR"/>
 *     &lt;enumeration value="CPOW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tDomainLNGroupCEnum")
@XmlEnum
public enum TDomainLNGroupCEnum {

    CILO,
    CSWI,
    CALH,
    CCGR,
    CPOW;

    public String value() {
        return name();
    }

    public static TDomainLNGroupCEnum fromValue(String v) {
        return valueOf(v);
    }

}
