//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGSE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGSE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tControlBlock">
 *       &lt;sequence>
 *         &lt;element name="MinTime" type="{http://www.iec.ch/61850/2006/SCL}tDurationInMilliSec" minOccurs="0"/>
 *         &lt;element name="MaxTime" type="{http://www.iec.ch/61850/2006/SCL}tDurationInMilliSec" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGSE", propOrder = {
    "minTime",
    "maxTime"
})
public class TGSE
    extends TControlBlock
{

    @XmlElement(name = "MinTime")
    protected TDurationInMilliSec minTime;
    @XmlElement(name = "MaxTime")
    protected TDurationInMilliSec maxTime;

    /**
     * Gets the value of the minTime property.
     * 
     * @return
     *     possible object is
     *     {@link TDurationInMilliSec }
     *     
     */
    public TDurationInMilliSec getMinTime() {
        return minTime;
    }

    /**
     * Sets the value of the minTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDurationInMilliSec }
     *     
     */
    public void setMinTime(TDurationInMilliSec value) {
        this.minTime = value;
    }

    /**
     * Gets the value of the maxTime property.
     * 
     * @return
     *     possible object is
     *     {@link TDurationInMilliSec }
     *     
     */
    public TDurationInMilliSec getMaxTime() {
        return maxTime;
    }

    /**
     * Sets the value of the maxTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDurationInMilliSec }
     *     
     */
    public void setMaxTime(TDurationInMilliSec value) {
        this.maxTime = value;
    }

}
