//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tP">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.iec.ch/61850/2006/SCL>tPAddr">
 *       &lt;attribute name="type" use="required" type="{http://www.iec.ch/61850/2006/SCL}tPTypeEnum" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tP", propOrder = {
    "value"
})
@XmlSeeAlso({
    TPOSIAPTitle.class,
    TPOSIPSEL.class,
    TPVLANID.class,
    TPOSISSEL.class,
    TPOSIAPInvoke.class,
    TPVLANPRIORITY.class,
    TPOSINSAP.class,
    TPIP.class,
    TPIPGATEWAY.class,
    TPOSIAEQualifier.class,
    TPOSITSEL.class,
    TPIPSUBNET.class,
    TPOSIAEInvoke.class,
    TPMACAddress.class,
    TPAPPID.class
})
public class TP {

    @XmlValue
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String value;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
