//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPredefinedCDCEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tPredefinedCDCEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="SPS"/>
 *     &lt;enumeration value="DPS"/>
 *     &lt;enumeration value="INS"/>
 *     &lt;enumeration value="ACT"/>
 *     &lt;enumeration value="ACD"/>
 *     &lt;enumeration value="SEC"/>
 *     &lt;enumeration value="BCR"/>
 *     &lt;enumeration value="MV"/>
 *     &lt;enumeration value="CMV"/>
 *     &lt;enumeration value="SAV"/>
 *     &lt;enumeration value="WYE"/>
 *     &lt;enumeration value="DEL"/>
 *     &lt;enumeration value="SEQ"/>
 *     &lt;enumeration value="HMV"/>
 *     &lt;enumeration value="HWYE"/>
 *     &lt;enumeration value="HDEL"/>
 *     &lt;enumeration value="SPC"/>
 *     &lt;enumeration value="DPC"/>
 *     &lt;enumeration value="INC"/>
 *     &lt;enumeration value="BSC"/>
 *     &lt;enumeration value="ISC"/>
 *     &lt;enumeration value="APC"/>
 *     &lt;enumeration value="SPG"/>
 *     &lt;enumeration value="ING"/>
 *     &lt;enumeration value="ASG"/>
 *     &lt;enumeration value="CURVE"/>
 *     &lt;enumeration value="DPL"/>
 *     &lt;enumeration value="LPL"/>
 *     &lt;enumeration value="CSD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tPredefinedCDCEnum")
@XmlEnum
public enum TPredefinedCDCEnum {

    SPS,
    DPS,
    INS,
    ACT,
    ACD,
    SEC,
    BCR,
    MV,
    CMV,
    SAV,
    WYE,
    DEL,
    SEQ,
    HMV,
    HWYE,
    HDEL,
    SPC,
    DPC,
    INC,
    BSC,
    ISC,
    APC,
    SPG,
    ING,
    ASG,
    CURVE,
    DPL,
    LPL,
    CSD;

    public String value() {
        return name();
    }

    public static TPredefinedCDCEnum fromValue(String v) {
        return valueOf(v);
    }

}
