//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tServiceFCEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tServiceFCEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="SG"/>
 *     &lt;enumeration value="BR"/>
 *     &lt;enumeration value="RP"/>
 *     &lt;enumeration value="LG"/>
 *     &lt;enumeration value="GO"/>
 *     &lt;enumeration value="GS"/>
 *     &lt;enumeration value="MS"/>
 *     &lt;enumeration value="US"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tServiceFCEnum")
@XmlEnum
public enum TServiceFCEnum {

    SG,
    BR,
    RP,
    LG,
    GO,
    GS,
    MS,
    US;

    public String value() {
        return name();
    }

    public static TServiceFCEnum fromValue(String v) {
        return valueOf(v);
    }

}
