//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tServiceSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServiceSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cbName" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="datSet" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServiceSettings")
@XmlSeeAlso({
    TReportSettings.class,
    TLogSettings.class,
    TSMVSettings.class,
    TGSESettings.class
})
public abstract class TServiceSettings {

    @XmlAttribute(name = "cbName")
    protected TServiceSettingsEnum cbName;
    @XmlAttribute(name = "datSet")
    protected TServiceSettingsEnum datSet;

    /**
     * Gets the value of the cbName property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getCbName() {
        if (cbName == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return cbName;
        }
    }

    /**
     * Sets the value of the cbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setCbName(TServiceSettingsEnum value) {
        this.cbName = value;
    }

    /**
     * Gets the value of the datSet property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getDatSet() {
        if (datSet == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return datSet;
        }
    }

    /**
     * Sets the value of the datSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setDatSet(TServiceSettingsEnum value) {
        this.datSet = value;
    }

}
