//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tServiceWithMaxAndMaxAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServiceWithMaxAndMaxAttributes">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tServiceWithMax">
 *       &lt;attribute name="maxAttributes" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServiceWithMaxAndMaxAttributes")
@XmlSeeAlso({
    TServiceWithMaxAndMaxAttributesAndModify.class
})
public class TServiceWithMaxAndMaxAttributes
    extends TServiceWithMax
{

    @XmlAttribute(name = "maxAttributes")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxAttributes;

    /**
     * Gets the value of the maxAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxAttributes() {
        return maxAttributes;
    }

    /**
     * Sets the value of the maxAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxAttributes(Long value) {
        this.maxAttributes = value;
    }

}
