//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="DynAssociation" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="SettingGroups" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="SGEdit" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *                   &lt;element name="ConfSG" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GetDirectory" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="GetDataObjectDefinition" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="DataObjectDirectory" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="GetDataSetValue" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="SetDataSetValue" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="DataSetDirectory" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfDataSet" type="{http://www.iec.ch/61850/2006/SCL}tServiceWithMaxAndMaxAttributesAndModify" minOccurs="0"/>
 *         &lt;element name="DynDataSet" type="{http://www.iec.ch/61850/2006/SCL}tServiceWithMaxAndMaxAttributes" minOccurs="0"/>
 *         &lt;element name="ReadWrite" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="TimerActivatedControl" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfReportControl" type="{http://www.iec.ch/61850/2006/SCL}tServiceWithMax" minOccurs="0"/>
 *         &lt;element name="GetCBValues" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfLogControl" type="{http://www.iec.ch/61850/2006/SCL}tServiceWithMax" minOccurs="0"/>
 *         &lt;element name="ReportSettings" type="{http://www.iec.ch/61850/2006/SCL}tReportSettings" minOccurs="0"/>
 *         &lt;element name="LogSettings" type="{http://www.iec.ch/61850/2006/SCL}tLogSettings" minOccurs="0"/>
 *         &lt;element name="GSESettings" type="{http://www.iec.ch/61850/2006/SCL}tGSESettings" minOccurs="0"/>
 *         &lt;element name="SMVSettings" type="{http://www.iec.ch/61850/2006/SCL}tSMVSettings" minOccurs="0"/>
 *         &lt;element name="GSEDir" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="GOOSE" type="{http://www.iec.ch/61850/2006/SCL}tServiceWithMax" minOccurs="0"/>
 *         &lt;element name="GSSE" type="{http://www.iec.ch/61850/2006/SCL}tServiceWithMax" minOccurs="0"/>
 *         &lt;element name="FileHandling" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfLNs" type="{http://www.iec.ch/61850/2006/SCL}tConfLNs" minOccurs="0"/>
 *         &lt;element name="ClientServices" type="{http://www.iec.ch/61850/2006/SCL}tClientServices" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServices", propOrder = {

})
public class TServices {

    @XmlElement(name = "DynAssociation")
    protected TServiceYesNo dynAssociation;
    @XmlElement(name = "SettingGroups")
    protected TServices.SettingGroups settingGroups;
    @XmlElement(name = "GetDirectory")
    protected TServiceYesNo getDirectory;
    @XmlElement(name = "GetDataObjectDefinition")
    protected TServiceYesNo getDataObjectDefinition;
    @XmlElement(name = "DataObjectDirectory")
    protected TServiceYesNo dataObjectDirectory;
    @XmlElement(name = "GetDataSetValue")
    protected TServiceYesNo getDataSetValue;
    @XmlElement(name = "SetDataSetValue")
    protected TServiceYesNo setDataSetValue;
    @XmlElement(name = "DataSetDirectory")
    protected TServiceYesNo dataSetDirectory;
    @XmlElement(name = "ConfDataSet")
    protected TServiceWithMaxAndMaxAttributesAndModify confDataSet;
    @XmlElement(name = "DynDataSet")
    protected TServiceWithMaxAndMaxAttributes dynDataSet;
    @XmlElement(name = "ReadWrite")
    protected TServiceYesNo readWrite;
    @XmlElement(name = "TimerActivatedControl")
    protected TServiceYesNo timerActivatedControl;
    @XmlElement(name = "ConfReportControl")
    protected TServiceWithMax confReportControl;
    @XmlElement(name = "GetCBValues")
    protected TServiceYesNo getCBValues;
    @XmlElement(name = "ConfLogControl")
    protected TServiceWithMax confLogControl;
    @XmlElement(name = "ReportSettings")
    protected TReportSettings reportSettings;
    @XmlElement(name = "LogSettings")
    protected TLogSettings logSettings;
    @XmlElement(name = "GSESettings")
    protected TGSESettings gseSettings;
    @XmlElement(name = "SMVSettings")
    protected TSMVSettings smvSettings;
    @XmlElement(name = "GSEDir")
    protected TServiceYesNo gseDir;
    @XmlElement(name = "GOOSE")
    protected TServiceWithMax goose;
    @XmlElement(name = "GSSE")
    protected TServiceWithMax gsse;
    @XmlElement(name = "FileHandling")
    protected TServiceYesNo fileHandling;
    @XmlElement(name = "ConfLNs")
    protected TConfLNs confLNs;
    @XmlElement(name = "ClientServices")
    protected TClientServices clientServices;

    /**
     * Gets the value of the dynAssociation property.
     *
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *
     */
    public TServiceYesNo getDynAssociation() {
        return dynAssociation;
    }

    /**
     * Sets the value of the dynAssociation property.
     *
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *
     */
    public void setDynAssociation(TServiceYesNo value) {
        this.dynAssociation = value;
    }

    /**
     * Gets the value of the settingGroups property.
     *
     * @return
     *     possible object is
     *     {@link TServices.SettingGroups }
     *
     */
    public TServices.SettingGroups getSettingGroups() {
        return settingGroups;
    }

    /**
     * Sets the value of the settingGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link TServices.SettingGroups }
     *
     */
    public void setSettingGroups(TServices.SettingGroups value) {
        this.settingGroups = value;
    }

    /**
     * Gets the value of the getDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetDirectory() {
        return getDirectory;
    }

    /**
     * Sets the value of the getDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetDirectory(TServiceYesNo value) {
        this.getDirectory = value;
    }

    /**
     * Gets the value of the getDataObjectDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetDataObjectDefinition() {
        return getDataObjectDefinition;
    }

    /**
     * Sets the value of the getDataObjectDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetDataObjectDefinition(TServiceYesNo value) {
        this.getDataObjectDefinition = value;
    }

    /**
     * Gets the value of the dataObjectDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getDataObjectDirectory() {
        return dataObjectDirectory;
    }

    /**
     * Sets the value of the dataObjectDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setDataObjectDirectory(TServiceYesNo value) {
        this.dataObjectDirectory = value;
    }

    /**
     * Gets the value of the getDataSetValue property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetDataSetValue() {
        return getDataSetValue;
    }

    /**
     * Sets the value of the getDataSetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetDataSetValue(TServiceYesNo value) {
        this.getDataSetValue = value;
    }

    /**
     * Gets the value of the setDataSetValue property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getSetDataSetValue() {
        return setDataSetValue;
    }

    /**
     * Sets the value of the setDataSetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setSetDataSetValue(TServiceYesNo value) {
        this.setDataSetValue = value;
    }

    /**
     * Gets the value of the dataSetDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getDataSetDirectory() {
        return dataSetDirectory;
    }

    /**
     * Sets the value of the dataSetDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setDataSetDirectory(TServiceYesNo value) {
        this.dataSetDirectory = value;
    }

    /**
     * Gets the value of the confDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMaxAndMaxAttributesAndModify }
     *     
     */
    public TServiceWithMaxAndMaxAttributesAndModify getConfDataSet() {
        return confDataSet;
    }

    /**
     * Sets the value of the confDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMaxAndMaxAttributesAndModify }
     *     
     */
    public void setConfDataSet(TServiceWithMaxAndMaxAttributesAndModify value) {
        this.confDataSet = value;
    }

    /**
     * Gets the value of the dynDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMaxAndMaxAttributes }
     *     
     */
    public TServiceWithMaxAndMaxAttributes getDynDataSet() {
        return dynDataSet;
    }

    /**
     * Sets the value of the dynDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMaxAndMaxAttributes }
     *     
     */
    public void setDynDataSet(TServiceWithMaxAndMaxAttributes value) {
        this.dynDataSet = value;
    }

    /**
     * Gets the value of the readWrite property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getReadWrite() {
        return readWrite;
    }

    /**
     * Sets the value of the readWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setReadWrite(TServiceYesNo value) {
        this.readWrite = value;
    }

    /**
     * Gets the value of the timerActivatedControl property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getTimerActivatedControl() {
        return timerActivatedControl;
    }

    /**
     * Sets the value of the timerActivatedControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setTimerActivatedControl(TServiceYesNo value) {
        this.timerActivatedControl = value;
    }

    /**
     * Gets the value of the confReportControl property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMax }
     *     
     */
    public TServiceWithMax getConfReportControl() {
        return confReportControl;
    }

    /**
     * Sets the value of the confReportControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMax }
     *     
     */
    public void setConfReportControl(TServiceWithMax value) {
        this.confReportControl = value;
    }

    /**
     * Gets the value of the getCBValues property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetCBValues() {
        return getCBValues;
    }

    /**
     * Sets the value of the getCBValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetCBValues(TServiceYesNo value) {
        this.getCBValues = value;
    }

    /**
     * Gets the value of the confLogControl property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMax }
     *     
     */
    public TServiceWithMax getConfLogControl() {
        return confLogControl;
    }

    /**
     * Sets the value of the confLogControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMax }
     *     
     */
    public void setConfLogControl(TServiceWithMax value) {
        this.confLogControl = value;
    }

    /**
     * Gets the value of the reportSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TReportSettings }
     *     
     */
    public TReportSettings getReportSettings() {
        return reportSettings;
    }

    /**
     * Sets the value of the reportSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TReportSettings }
     *     
     */
    public void setReportSettings(TReportSettings value) {
        this.reportSettings = value;
    }

    /**
     * Gets the value of the logSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TLogSettings }
     *     
     */
    public TLogSettings getLogSettings() {
        return logSettings;
    }

    /**
     * Sets the value of the logSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLogSettings }
     *     
     */
    public void setLogSettings(TLogSettings value) {
        this.logSettings = value;
    }

    /**
     * Gets the value of the gseSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TGSESettings }
     *     
     */
    public TGSESettings getGSESettings() {
        return gseSettings;
    }

    /**
     * Sets the value of the gseSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGSESettings }
     *     
     */
    public void setGSESettings(TGSESettings value) {
        this.gseSettings = value;
    }

    /**
     * Gets the value of the smvSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TSMVSettings }
     *     
     */
    public TSMVSettings getSMVSettings() {
        return smvSettings;
    }

    /**
     * Sets the value of the smvSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSMVSettings }
     *     
     */
    public void setSMVSettings(TSMVSettings value) {
        this.smvSettings = value;
    }

    /**
     * Gets the value of the gseDir property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGSEDir() {
        return gseDir;
    }

    /**
     * Sets the value of the gseDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGSEDir(TServiceYesNo value) {
        this.gseDir = value;
    }

    /**
     * Gets the value of the goose property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMax }
     *     
     */
    public TServiceWithMax getGOOSE() {
        return goose;
    }

    /**
     * Sets the value of the goose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMax }
     *     
     */
    public void setGOOSE(TServiceWithMax value) {
        this.goose = value;
    }

    /**
     * Gets the value of the gsse property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMax }
     *     
     */
    public TServiceWithMax getGSSE() {
        return gsse;
    }

    /**
     * Sets the value of the gsse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMax }
     *     
     */
    public void setGSSE(TServiceWithMax value) {
        this.gsse = value;
    }

    /**
     * Gets the value of the fileHandling property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getFileHandling() {
        return fileHandling;
    }

    /**
     * Sets the value of the fileHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setFileHandling(TServiceYesNo value) {
        this.fileHandling = value;
    }

    /**
     * Gets the value of the confLNs property.
     * 
     * @return
     *     possible object is
     *     {@link TConfLNs }
     *     
     */
    public TConfLNs getConfLNs() {
        return confLNs;
    }

    /**
     * Sets the value of the confLNs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TConfLNs }
     *     
     */
    public void setConfLNs(TConfLNs value) {
        this.confLNs = value;
    }

    /**
     * Gets the value of the clientServices property.
     * 
     * @return
     *     possible object is
     *     {@link TClientServices }
     *     
     */
    public TClientServices getClientServices() {
        return clientServices;
    }

    /**
     * Sets the value of the clientServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClientServices }
     *     
     */
    public void setClientServices(TClientServices value) {
        this.clientServices = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="SGEdit" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
     *         &lt;element name="ConfSG" type="{http://www.iec.ch/61850/2006/SCL}tServiceYesNo" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SettingGroups {

        @XmlElement(name = "SGEdit")
        protected TServiceYesNo sgEdit;
        @XmlElement(name = "ConfSG")
        protected TServiceYesNo confSG;

        /**
         * Gets the value of the sgEdit property.
         * 
         * @return
         *     possible object is
         *     {@link TServiceYesNo }
         *     
         */
        public TServiceYesNo getSGEdit() {
            return sgEdit;
        }

        /**
         * Sets the value of the sgEdit property.
         * 
         * @param value
         *     allowed object is
         *     {@link TServiceYesNo }
         *     
         */
        public void setSGEdit(TServiceYesNo value) {
            this.sgEdit = value;
        }

        /**
         * Gets the value of the confSG property.
         * 
         * @return
         *     possible object is
         *     {@link TServiceYesNo }
         *     
         */
        public TServiceYesNo getConfSG() {
            return confSG;
        }

        /**
         * Sets the value of the confSG property.
         * 
         * @param value
         *     allowed object is
         *     {@link TServiceYesNo }
         *     
         */
        public void setConfSG(TServiceYesNo value) {
            this.confSG = value;
        }

    }

}
