//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tSettingControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSettingControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tUnNaming">
 *       &lt;attribute name="numOfSGs" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="actSG" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="1" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSettingControl")
public class TSettingControl
    extends TUnNaming
{

    @XmlAttribute(name = "numOfSGs", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long numOfSGs;
    @XmlAttribute(name = "actSG")
    @XmlSchemaType(name = "unsignedInt")
    protected Long actSG;

    /**
     * Gets the value of the numOfSGs property.
     * 
     */
    public long getNumOfSGs() {
        return numOfSGs;
    }

    /**
     * Sets the value of the numOfSGs property.
     * 
     */
    public void setNumOfSGs(long value) {
        this.numOfSGs = value;
    }

    /**
     * Gets the value of the actSG property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getActSG() {
        if (actSG == null) {
            return  1L;
        } else {
            return actSG;
        }
    }

    /**
     * Sets the value of the actSG property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setActSG(Long value) {
        this.actSG = value;
    }

}
