//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tSMVSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSMVSettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tServiceSettings">
 *       &lt;sequence>
 *         &lt;element name="SmpRate" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="svID" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="optFields" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="smpRate" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSMVSettings", propOrder = {
    "smpRate"
})
public class TSMVSettings
    extends TServiceSettings
{

    @XmlElement(name = "SmpRate", required = true)
    protected List<BigDecimal> smpRate;
    @XmlAttribute(name = "svID")
    protected TServiceSettingsEnum svID;
    @XmlAttribute(name = "optFields")
    protected TServiceSettingsEnum optFields;
    @XmlAttribute(name = "smpRate")
    protected TServiceSettingsEnum smpRateAttribute;

    /**
     * Gets the value of the smpRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smpRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmpRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getSmpRate() {
        if (smpRate == null) {
            smpRate = new ArrayList<BigDecimal>();
        }
        return this.smpRate;
    }

    /**
     * Gets the value of the svID property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getSvID() {
        if (svID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return svID;
        }
    }

    /**
     * Sets the value of the svID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setSvID(TServiceSettingsEnum value) {
        this.svID = value;
    }

    /**
     * Gets the value of the optFields property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getOptFields() {
        if (optFields == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return optFields;
        }
    }

    /**
     * Sets the value of the optFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setOptFields(TServiceSettingsEnum value) {
        this.optFields = value;
    }

    /**
     * Gets the value of the smpRateAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getSmpRateAttribute() {
        if (smpRateAttribute == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return smpRateAttribute;
        }
    }

    /**
     * Sets the value of the smpRateAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setSmpRateAttribute(TServiceSettingsEnum value) {
        this.smpRateAttribute = value;
    }

}
