//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tTerminal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTerminal">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tUnNaming">
 *       &lt;attribute name="name" type="{http://www.iec.ch/61850/2006/SCL}tAnyName" default="" />
 *       &lt;attribute name="connectivityNode" use="required" type="{http://www.iec.ch/61850/2006/SCL}tRef" />
 *       &lt;attribute name="substationName" use="required" type="{http://www.iec.ch/61850/2006/SCL}tName" />
 *       &lt;attribute name="voltageLevelName" use="required" type="{http://www.iec.ch/61850/2006/SCL}tName" />
 *       &lt;attribute name="bayName" use="required" type="{http://www.iec.ch/61850/2006/SCL}tName" />
 *       &lt;attribute name="cNodeName" use="required" type="{http://www.iec.ch/61850/2006/SCL}tName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTerminal")
public class TTerminal
    extends TUnNaming
{

    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "connectivityNode", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connectivityNode;
    @XmlAttribute(name = "substationName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String substationName;
    @XmlAttribute(name = "voltageLevelName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String voltageLevelName;
    @XmlAttribute(name = "bayName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bayName;
    @XmlAttribute(name = "cNodeName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cNodeName;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the connectivityNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectivityNode() {
        return connectivityNode;
    }

    /**
     * Sets the value of the connectivityNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectivityNode(String value) {
        this.connectivityNode = value;
    }

    /**
     * Gets the value of the substationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstationName() {
        return substationName;
    }

    /**
     * Sets the value of the substationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstationName(String value) {
        this.substationName = value;
    }

    /**
     * Gets the value of the voltageLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoltageLevelName() {
        return voltageLevelName;
    }

    /**
     * Sets the value of the voltageLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoltageLevelName(String value) {
        this.voltageLevelName = value;
    }

    /**
     * Gets the value of the bayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBayName() {
        return bayName;
    }

    /**
     * Sets the value of the bayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBayName(String value) {
        this.bayName = value;
    }

    /**
     * Gets the value of the cNodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNodeName() {
        return cNodeName;
    }

    /**
     * Sets the value of the cNodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNodeName(String value) {
        this.cNodeName = value;
    }

}
