//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tTransformerWinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTransformerWinding">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tAbstractConductingEquipment">
 *       &lt;sequence>
 *         &lt;element name="TapChanger" type="{http://www.iec.ch/61850/2006/SCL}tTapChanger" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.iec.ch/61850/2006/SCL}tTransformerWindingEnum" fixed="PTW" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTransformerWinding", propOrder = {
    "tapChanger"
})
public class TTransformerWinding
    extends TAbstractConductingEquipment
{

    @XmlElement(name = "TapChanger")
    protected TTapChanger tapChanger;
    @XmlAttribute(name = "type", required = true)
    protected TTransformerWindingEnum type;

    /**
     * Gets the value of the tapChanger property.
     * 
     * @return
     *     possible object is
     *     {@link TTapChanger }
     *     
     */
    public TTapChanger getTapChanger() {
        return tapChanger;
    }

    /**
     * Sets the value of the tapChanger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTapChanger }
     *     
     */
    public void setTapChanger(TTapChanger value) {
        this.tapChanger = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TTransformerWindingEnum }
     *     
     */
    public TTransformerWindingEnum getType() {
        if (type == null) {
            return TTransformerWindingEnum.PTW;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransformerWindingEnum }
     *     
     */
    public void setType(TTransformerWindingEnum value) {
        this.type = value;
    }

}
