//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 12:03:20 PM MSK 
//


package ru.smarteps.scl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTrgOptControlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tTrgOptControlEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="dchg"/>
 *     &lt;enumeration value="qchg"/>
 *     &lt;enumeration value="dupd"/>
 *     &lt;enumeration value="period"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tTrgOptControlEnum")
@XmlEnum
public enum TTrgOptControlEnum {

    @XmlEnumValue("dchg")
    DCHG("dchg"),
    @XmlEnumValue("qchg")
    QCHG("qchg"),
    @XmlEnumValue("dupd")
    DUPD("dupd"),
    @XmlEnumValue("period")
    PERIOD("period"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    TTrgOptControlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTrgOptControlEnum fromValue(String v) {
        for (TTrgOptControlEnum c: TTrgOptControlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
